import { useState } from "react";
import { motion } from "framer-motion";
import { Card } from "../ui/Card";
import { Button } from "../ui/Button";
import { Dialog } from "../ui/Dialog";
import { useLang } from "../../context/LanguageContext";
import type { SpecialistRef } from "../../types";

export function ReferralSuggestionCard({
  specialist,
  onGenerate,
  pending,
}: {
  specialist: SpecialistRef;
  onGenerate: () => void;
  pending?: boolean;
}) {
  const { t } = useLang();
  const [open, setOpen] = useState(false);
  const [copied, setCopied] = useState(false);

  function handleGenerate() {
    onGenerate();
    setOpen(true);
  }

  const letterText = `SAHAYAK COMMUNITY HOSPITAL REFERRAL LETTER\nDate: ${new Date().toLocaleDateString()}\n\nRECOMMENDED HOSPITAL OR SPECIALIST CLINIC:\n- Primary: ${specialist.primary}\n${specialist.secondary ? `- Secondary Option: ${specialist.secondary}\n` : ""}\nWHY THIS DOCTOR VISIT IS RECOMMENDED:\n${specialist.reason}\n\nGenerated by Sahayak Smart Community Health Guide.`;

  return (
    <>
      <motion.div initial={{ opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.2 }}>
        <Card className="p-5 border-l-4 border-l-brand-primary shadow-md hover:shadow-lg transition-all flex flex-col justify-between h-full bg-surface">
          <div>
            <div className="flex items-center justify-between mb-1">
              <h3 className="font-display text-lg font-bold text-text-primary">{t("breakdown.referral")}</h3>
              <span className="text-[11px] uppercase px-2.5 py-0.5 rounded-full bg-brand-primary/15 text-brand-primary font-bold border border-brand-primary/20">
                Recommended Doctor
              </span>
            </div>
            <p className="text-xs text-text-secondary">Calculated using verified health screening rules</p>
            
            <div className="mt-4 font-display text-2xl font-black text-brand-primary tracking-tight">
              {specialist.primary}
            </div>
            {specialist.secondary && (
              <div className="text-sm font-semibold text-text-secondary mt-1">
                + {specialist.secondary}
              </div>
            )}
            <div className="mt-3 text-xs text-text-primary bg-surface-elevated p-3.5 rounded-xl border border-border/70 leading-relaxed">
              <span className="font-bold block mb-1 text-text-muted uppercase text-[10px]">Why this doctor visit is recommended:</span>
              <p>{specialist.reason}</p>
              <p className="text-[11px] text-text-secondary mt-2 border-t border-border/50 pt-2 font-medium">
                ℹ️ <strong>Why this letter is helpful:</strong> Handing this document to a hospital specialist immediately explains your symptoms and tests so you don't have to remember confusing medical vocabulary yourself!
              </p>
            </div>
          </div>

          <Button
            onClick={handleGenerate}
            variant="primary"
            size="lg"
            className="mt-5 w-full font-bold shadow-md hover:shadow-xl transition-all py-3.5"
            loading={pending}
          >
            📋 {t("breakdown.generate")} Letter & Summary
          </Button>
        </Card>
      </motion.div>

      {/* Referral Letter Preview Dialog */}
      <Dialog open={open} onClose={() => setOpen(false)} title="🏥 Official Sahayak Doctor Referral Letter">
        <div className="space-y-4 text-sm text-text-primary">
          <div className="p-5 rounded-2xl bg-[#0A1622] text-slate-100 font-mono text-xs space-y-3 border border-[#1E2F42] shadow-inner">
            <div className="flex justify-between items-center border-b border-slate-700/60 pb-2.5 font-bold text-cyan-400 text-sm">
              <span>SAHAYAK REFERRAL LETTER</span>
              <span>{new Date().toLocaleDateString()}</span>
            </div>
            <div>
              <span className="text-slate-400 block text-[10px] uppercase">Recommended Hospital or Clinic:</span>
              <span className="text-base font-bold text-white">{specialist.primary}</span>
              {specialist.secondary && <span className="block text-slate-300 text-xs mt-0.5"> (Alternative Option: {specialist.secondary})</span>}
            </div>
            <div className="pt-1">
              <span className="text-slate-400 block text-[10px] uppercase mb-1">Why Specialist Hospital Care is Needed:</span>
              <p className="text-slate-100 leading-relaxed font-sans text-xs bg-black/20 p-3 rounded-lg border border-white/5">{specialist.reason}</p>
            </div>
            <div className="pt-2.5 border-t border-slate-700/60 text-[10px] text-slate-400 flex justify-between font-bold">
              <span>STATUS: READY FOR DOCTOR / HOSPITAL</span>
              <span className="text-emerald-400">AUTH: SAHAYAK RULES v1.0</span>
            </div>
          </div>

          <div className="grid grid-cols-2 gap-3 pt-2">
            <Button
              variant="subtle"
              size="sm"
              onClick={() => {
                navigator.clipboard?.writeText(letterText).then(() => {
                  setCopied(true);
                  setTimeout(() => setCopied(false), 2000);
                });
              }}
              className="w-full font-bold py-3"
            >
              {copied ? "✓ Copied to Clipboard!" : "📋 Copy Referral Text"}
            </Button>
            <Button
              variant="primary"
              size="sm"
              onClick={() => window.print()}
              className="w-full font-bold py-3"
            >
              🖨️ Print Doctor Letter
            </Button>
          </div>

          <Button variant="ghost" size="sm" onClick={() => setOpen(false)} className="w-full mt-2 text-xs">
            Close Document Preview
          </Button>
        </div>
      </Dialog>
    </>
  );
}
